spring:
  datasource:
    name: oa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vincent
    password: vincent
    url: jdbc:mysql://localhost:3306/oa?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC